/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Web Totals",
  "favicon": "img/logo.png",
  "url": "https://web-totals.vercel.app",
  "baseUrl": "/",
  "organizationName": "hunghg255",
  "projectName": "web-totals",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "webpack": {},
  "clientModules": [
    "/Users/kengzone/Documents/project/web-questions/snackPlayerInitializer.js"
  ],
  "scripts": [
    {
      "src": "https://cdn.jsdelivr.net/npm/focus-visible@5.2.0/dist/focus-visible.min.js",
      "defer": true
    },
    {
      "src": "https://widget.surveymonkey.com/collect/website/js/tRaiETqnLgj758hTBazgd8ryO5qrZo8Exadq9qmt1wtm4_2FdZGEAKHDFEt_2BBlwwM4.js",
      "defer": true
    },
    {
      "src": "https://snack.expo.dev/embed.js",
      "defer": true
    }
  ],
  "plugins": [
    [
      "content-docs",
      {
        "id": "issues",
        "path": "issues",
        "routeBasePath": "issues",
        "sidebarPath": "/Users/kengzone/Documents/project/web-questions/sidebars.js",
        "remarkPlugins": [
          null,
          [
            null,
            {
              "sync": true,
              "converters": [
                "yarn",
                "pnpm",
                [
                  "bun",
                  null
                ]
              ]
            }
          ]
        ]
      }
    ],
    [
      "content-docs",
      {
        "id": "questions",
        "path": "questions",
        "routeBasePath": "questions",
        "sidebarPath": "/Users/kengzone/Documents/project/web-questions/sidebars.js",
        "remarkPlugins": [
          [
            null,
            {
              "sync": true,
              "converters": [
                "yarn",
                "pnpm",
                [
                  "bun",
                  null
                ]
              ]
            }
          ]
        ]
      }
    ],
    "@docusaurus/theme-live-codeblock"
  ],
  "themes": [
    "@docusaurus/theme-mermaid"
  ],
  "markdown": {
    "mermaid": true,
    "format": "mdx",
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    }
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "/Users/kengzone/Documents/project/web-questions/sidebars.js",
          "showLastUpdateAuthor": true,
          "showLastUpdateTime": true,
          "sidebarCollapsible": true,
          "editUrl": "https://github.com/hunghg255/web-totals/tree/main",
          "remarkPlugins": [
            null,
            [
              null,
              {
                "sync": true,
                "converters": [
                  "yarn",
                  "pnpm",
                  [
                    "bun",
                    null
                  ]
                ]
              }
            ]
          ]
        },
        "pages": {
          "remarkPlugins": [
            null,
            {
              "sync": true,
              "converters": [
                "yarn",
                "pnpm",
                [
                  "bun",
                  null
                ]
              ]
            }
          ]
        },
        "blog": {
          "blogTitle": "Blogs",
          "blogDescription": "Blogs",
          "blogSidebarTitle": "Blogs",
          "blogSidebarCount": 10,
          "showReadingTime": true,
          "editUrl": "https://github.com/hunghg255/web-totals/tree/main",
          "remarkPlugins": [
            [
              null,
              {
                "sync": true,
                "converters": [
                  "yarn",
                  "pnpm",
                  [
                    "bun",
                    null
                  ]
                ]
              }
            ]
          ]
        },
        "theme": {
          "customCss": "/Users/kengzone/Documents/project/web-questions/src/css/custom.css"
        },
        "googleAnalytics": {
          "trackingID": "G-WZW3J8S7EF"
        },
        "gtag": {
          "trackingID": "G-72XCT3FHGJ"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "/img/unicorn.png",
    "navbar": {
      "title": "Web Totals",
      "logo": {
        "alt": "Web Totals",
        "src": "/img/logo.png"
      },
      "items": [
        {
          "type": "doc",
          "position": "right",
          "label": "Docs",
          "docId": "intro"
        },
        {
          "to": "/blog",
          "label": "Blog",
          "position": "right"
        },
        {
          "to": "/issues",
          "label": "Issues",
          "position": "right",
          "activeBaseRegex": "/issues"
        },
        {
          "to": "/questions",
          "label": "Questions",
          "position": "right",
          "activeBaseRegex": "/questions"
        },
        {
          "type": "docsVersionDropdown",
          "position": "right",
          "dropdownItemsBefore": [],
          "dropdownItemsAfter": []
        },
        {
          "type": "localeDropdown",
          "position": "right",
          "dropdownItemsBefore": [],
          "dropdownItemsAfter": []
        },
        {
          "href": "https://github.com/hunghg255/web-totals",
          "label": "GitHub",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "colorMode": {
      "defaultMode": "dark",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "RSS Feed",
          "items": [
            {
              "label": "RSS",
              "href": "https://web-totals.vercel.app/sitemap.xml"
            }
          ]
        },
        {
          "title": "Contact",
          "items": [
            {
              "label": "Twitter",
              "href": "https://twitter.com/hunghg255"
            },
            {
              "label": "Facebook",
              "href": "https://facebook.com/hunghg255"
            },
            {
              "label": "Portfolio",
              "href": "https://hung.thedev.id"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "GitHub",
              "href": "https://github.com/hunghg255"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2023 Web Totals"
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "algolia": {
      "appId": "N1ZOY7XK8O",
      "apiKey": "93bc1d5b9e29191f5bd0758d04332c34",
      "indexName": "webtotals",
      "contextualSearch": true,
      "externalUrlRegex": "web-totals\\.vercel.app|web-totals\\.vercel.app",
      "searchParameters": {},
      "searchPagePath": "search"
    },
    "liveCodeBlock": {
      "playgroundPosition": "bottom"
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    },
    "mermaid": {
      "theme": {
        "dark": "dark",
        "light": "default"
      },
      "options": {}
    }
  },
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "path": "i18n",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "headTags": [],
  "stylesheets": [],
  "tagline": "",
  "titleDelimiter": "|",
  "noIndex": false
};
